// Draft issue / PR templates (contract §28). The output is a DRAFT for human review — it is
// never submitted. A patch proposal is included only when there is public source + a
// CONTRIBUTING guide + a verifiable fix.

export interface DraftIssueInput {
  readonly title: string
  readonly facts: readonly string[]
  readonly hypothesis: string
  readonly repro: string
  readonly replay: string
  readonly versions: Readonly<Record<string, string>>
  readonly impact: string
}

export function draftIssue(input: DraftIssueInput): string {
  return `<!-- DRAFT — generated by SupaKernel's upstream-evidence lab. NOT submitted.
     A human must review, verify against an existing issue search, and decide. -->

# ${input.title}

## Observed (facts only)

${input.facts.map((f) => `- ${f}`).join('\n')}

## Environment

${Object.entries(input.versions)
  .map(([k, v]) => `- ${k}: ${v}`)
  .join('\n')}

## Minimal reproducer

\`\`\`sh
${input.repro.trim()}
\`\`\`

One-command replay of the recorded evidence (offline):

\`\`\`sh
${input.replay}
\`\`\`

## Causal hypothesis (NOT a fact — for maintainer evaluation)

${input.hypothesis}

## Impact

${input.impact}

## Notes

- Behavioural reimplementation context only; no upstream code was copied.
- This report was auto-drafted; a maintainer should check for an existing issue first.
`
}

export function draftPatchProposal(input: {
  file: string
  before: string
  after: string
  rationale: string
}): string {
  return `## Proposed change (draft — verify before opening a PR)

\`${input.file}\`

\`\`\`diff
${input.before
  .split('\n')
  .map((l) => `- ${l}`)
  .join('\n')}
${input.after
  .split('\n')
  .map((l) => `+ ${l}`)
  .join('\n')}
\`\`\`

${input.rationale}
`
}
