/**
 * Generate the Management API artifacts deterministically (contract §16, §30 L9):
 *   - packages/management/openapi.gen.json  — the pinned SupaKernel Management OpenAPI document
 *   - packages/management/src/management-api.gen.ts  — types via openapi-typescript@7.13.0
 *
 * CI runs `pnpm generate && git diff --exit-code`; a stale artifact fails the build.
 *
 *   node scripts/generate-management-api.mts
 */
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import { repoRoot } from './lib/evidence.mts'

async function main(): Promise<void> {
  // Load the OpenAPI document from the management source (single source of truth). `openapi.ts`
  // has only a type-only import, so Node's type stripping runs it without a build step.
  const mod = (await import(
    new URL('../packages/management/src/openapi.ts', import.meta.url).href
  )) as { MANAGEMENT_OPENAPI: unknown }
  const doc = mod.MANAGEMENT_OPENAPI

  const jsonPath = join(repoRoot, 'packages/management/openapi.gen.json')
  const canonical = `${JSON.stringify(doc, null, 2)}\n`
  await writeFile(jsonPath, canonical)

  const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0], {
    alphabetize: true,
    immutable: true,
  })
  const header =
    '// GENERATED by scripts/generate-management-api.mts — do not edit.\n' +
    `// source sha256: ${createHash('sha256').update(canonical).digest('hex')}\n\n`
  const tsPath = join(repoRoot, 'packages/management/src/management-api.gen.ts')
  await writeFile(tsPath, header + astToString(ast))

  // sanity: the file we just wrote must parse back to the same document
  const back = JSON.parse(await readFile(jsonPath, 'utf8'))
  if (JSON.stringify(back) !== JSON.stringify(doc)) {
    process.stderr.write('generate-management-api: round-trip mismatch\n')
    process.exit(1)
  }
  process.stdout.write(
    `generated management OpenAPI (${Object.keys((doc as { paths: object }).paths).length} paths) + types\n`,
  )
}

await main()
